Api producto
AlexHRodrii/backend-abp pull request #12
Opened 2023-03-22 16:57 UTC by Danielluengo15

2023-03-22 19:54 UTC, AlexHRodrii requested changes
Arreglar las pequeñas cosillas y lo más importante el tema de la petición parametrizada

2023-03-22 19:54 UTC, AlexHRodrii commented on app/Http/Controllers/ProductoController.php
> +        $products = Producto::all();
Sería conveniente usar un try catch aquí también para tratar cualquier posible excepción

2023-03-22 19:54 UTC, AlexHRodrii commented on app/Http/Controllers/ProductoController.php
> +                'descripcion_producto' => $request->get('descripcion_producto'),
En la request es conveniente que usemos camelCase en las peticiones
`$request->get('descripcionProducto')`

2023-03-22 19:54 UTC, AlexHRodrii commented on app/Http/Controllers/ProductoController.php
> +            $resultResponse->setStatusCode(ResultResponse::ERROR_ELEMENT_NOT_FOUND_CODE);
Revisar con detalle los códigos de error, aquí por ejemplo siempre se está devolviendo un código 404 cuando a lo mejor no ha sido ese el problema

2023-03-22 19:54 UTC, AlexHRodrii commented on app/Libs/ResultResponse.php
> +    const ERROR_CODE = 300;
300 no es un código de error, este indica redirección

2023-03-22 19:54 UTC, AlexHRodrii commented on app/Libs/ResultResponse.php
> +
Añadir algunos códigos y mensajes de error y de éxito más:
201 -> Created (Para los post exitosos)
204 -> No content (Para los delete exitosos)
400 -> Bad request
500 -> Internal server error

2023-03-22 19:54 UTC, AlexHRodrii commented on app/Http/Controllers/ProductoController.php
> +        return response()->json($resultResponse);
¡¡¡Recordemos que el GET general tenía que aceptar parámetros de búsqueda según decía el enunciado!!!

![image](https://user-images.githubusercontent.com/60890872/227020593-3e46f75e-5d4d-43c0-9a2a-76e4323292e9.png)

2023-03-23 19:46 UTC, Danielluengo15 commented on app/Http/Controllers/ProductoController.php
> +            $resultResponse->setStatusCode(ResultResponse::ERROR_ELEMENT_NOT_FOUND_CODE);
No tengo muy claro como hacer esto, no esta implementado por ahora

2023-03-23 19:47 UTC, Danielluengo15 commented on app/Http/Controllers/ProductoController.php
> +        return response()->json($resultResponse);
Ahora mismo solo busca con "any", es decir, cualquier campo

2023-03-24 17:16 UTC, AlexHRodrii approved these changes

2023-03-24 17:17 UTC, merged